on: [push]

jobs:
  cv_job:
    runs-on: ubuntu-latest
    name: Build CI
    steps:
      - name: CV step
        id: first
        uses: LimiO/CV@master
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: main.pdf
      - uses: actions/checkout@v2
        with:
          ref: 'artifacts'
          path: 'artifacts'
      - run: |
          cd artifacts
          mv ../file.txt file.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add main.pdf
          git commit -m "add main.pdf"
          git push origin artifacts
