on: [push]

jobs:
  cv_job:
    runs-on: ubuntu-latest
    name: Build CI
    steps:
      - name: CV step
        id: first
        uses: LimiO/CV@master
        run: echo "::set-env name=BRANCH_NAME::${GITHUB_REF##*/}"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BRANCH_NAME }}-artifact
          path: file.txt