on: [push]

jobs:
  cv_job:
    runs-on: ubuntu-latest
    name: Build CI
    steps:
      - name: CV step
        id: first
        uses: LimiO/CV@master
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: file.txt
      - run: |
          ls
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: ${{ github.workspace }}
      - uses: actions/checkout@v2
      - run: |
          ls